### ISSUE TITLE
Add Python 3.12-dev to the matrix

### ISSUE THREAD

**Issue by naufraghi** [naufraghi/tinyaes-py#32]
Something like:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(version, 'dev') }}
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-dev"]
```

- https://pythontest.com/testing-with-python-3-12/
- https://docs.github.com/en/actions/learn-github-actions/expressions#endswith
